[package]
name = "gasoline"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = {version = "1.4.6", features = ["mysql"]}
clap = "2.33.3"
dotenv = "0.15.0"